site_name: DelMoro
site_url: https://yourusername.github.io/DelMoro
site_description: Documentation for DelMoro Pipeline
site_author: Firas Zemzem

theme:
  name: readthedocs
  theme:
     - content.code.copy
     - content.tabs
     - content.toggle


extra_css:
  - css/custom.css

extra_javascript:
  - assets/scripts.js

nav:
  - Home: index.md
  - Quickstart: 1quickstart.md
  - Pipeline Overview:
      - Workflow Structure: 2overview.md
      - Requirements: 3requirements.md
      - Inputs & Outputs: 4io.md
  - Configuration:
      - Parameters: 5parameters.md
      - Config Files: 6config.md
  - Running the Pipeline: 7running.md
  - Development:
      - Changelog: 8changelog.md
      - About: 9about.md

repo_url: https://github.com/othmanResearch/DelMoro.git
repo_name: othmanResearch/DelMoro

plugins:
  - search
  - glightbox
markdown_extensions:
  - toc:
      permalink: true
  - admonition
  - codehilite
  - footnotes
  - tables
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight

