name: Deploy MkDocs site

on:
  push:
    branches:
      - docs  # working/docs source branch

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install mkdocs-material mkdocs-mermaid2-plugin mkdocs-glightbox pillow cairosvg

      - name: Deploy to GitHub Pages (doc branch)
        run: mkdocs gh-deploy --force --remote-branch public
